name = "SubHalos"
uuid = "eb1a1f42-d770-44a6-854c-d52d525a41cb"
authors = ["Gaétan Facchinetti"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
